spring:
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///flowable_platform
    username: flowable
    password: flowable
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/migration/test-data

  autoconfigure:
    exclude:
      - org.springdoc.springdoc-openapi-starter-webmvc-autoconfiguration

flowable:
  database-schema-update: true

logging:
  level:
    com.flowable.platform: DEBUG
    org.flowable: INFO
    org.springframework.security: INFO
    org.testcontainers: INFO
